#!/bin/tcsh -f

make -f mymake

echo
echo "+++++++Part 1 Test 1++++++++" 
./mynetwork data1 < input11

echo
echo "+++++++Part 1 Test 2++++++++" 
./mynetwork data2 < input12

echo
echo "+++++++Part 1 Test 3++++++++" 
./mynetwork data3 < input13

echo
echo "+++++++Part 1 Test 4++++++++" 
./mynetwork data4 < input14

echo
echo "+++++++Part 2 Test 1++++++++"
./mynetwork data1 < input21

echo
echo "+++++++Part 2 Test 2++++++++"
./mynetwork data2 < input22

echo
echo "+++++++Part 2 Test 3++++++++"
./mynetwork data3 < input23

echo
echo "+++++++Part 2 Test 4++++++++" 
./mynetwork data4 < input24
